#TOUCH THIS IF YOU WANT A RECKED CONFIG!
version: 1.5

#The prefix you use to create a sign
#Date format, more information at http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html 
date-format: 'dd/MM HH:mm'

#Configurable online signs, add %name% for name and %date% for date
online-sign:
  1: '&a%name%'
  2: '&aEn línea'
  3: ' '
  4: ' '

#Configurable offline signs, add %name% for name and %date% for date
offline-sign:
  1: '&c%name%'
  2: '&cDesconectado'
  3: '&cdesde'
  4: '&c%date%'